name: flutter_date_range_picker
description: A Flutter package for all platform which provides a custom date picker
publish_to: 'none'
version: 1.0.1

environment:
  sdk: ">=2.14.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  intl: ^0.18.0

  # syncfusion_flutter_datepicker: ^20.2.49

  syncfusion_flutter_datepicker:
    git: https://github.com/irwan75/syncfusion_flutter_datepicker.git
  #   path: ../syncfusion-flutter-datepicker

  # pattern_formatter: 2.0.0
  pattern_formatter:
    git: https://github.com/irwan75/flutter_pattern_formatter.git
  
  flutter_svg: 2.0.2

  debounce_throttle: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
